### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by pdeelen** [cyberjunky/home-assistant-p2000#19]
Hi, 

After the configuration part, i did a reboot. 
I receive a error message;
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'feeds.livep2000.nl'. (_ssl.c:1076)

The problem is that livep2000.nl has not a wildcard certificate. 
So the URL https://feeds.livep2000.nl/ is not validated. 

Kind regards, 
Paul

**Comment by poudenes** [comment]
Suddenly I have the same issue... Worked great. Maybe something with the site itself?

**Comment by Wummeke** [comment]
The certificate that is used on https://feeds.livep2000.nl/ is issued for www.livep2000.nl or livep2000.nl. So there is a mismatch with the URL for the feeds. The problem is caused by the site itself (the owner forgot to add a so called subject alternative name for feeds.livep2000.nl in his/her certificate request).
Perhaps there is a way to ignore this in the python code of the integration, but I am not  really skilled in that field :)

**Comment by Martinvdm** [comment]
same issue, home assistant is giving an error about is also:
```
Traceback (most recent call last):,
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state,
    await self.async_device_update(),
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update,
    await self.async_update(),
  File "/config/custom_components/p2000/sensor.py", line 262, in async_update,
    await self._data.async_update(),
  File "/config/custom_components/p2000/sensor.py", line 118, in async_update,
    self._url, self._etag, self._modfied,
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run,
    result = self.fn(*self.args, **self.kwargs),
  File "/usr/local/lib/python3.7/site-packages/feedparser/api.py", line 230, in parse,
    data = _open_resource(url_file_stream_or_string, etag, modified, agent, referrer, handlers, request_headers, result),
  File "/usr/local/lib/python3.7/site-packages/feedparser/api.py", line 138, in _open_resource,
    return http.get(url_file_stream_or_string, etag, modified, agent, referrer, handlers, request_headers, result),
  File "/usr/local/lib/python3.7/site-packages/feedparser/http.py", line 175, in get,
    f = opener.open(request),
  File "/usr/local/lib/python3.7/urllib/request.py", line 525, in open,
    response = self._open(req, data),
  File "/usr/local/lib/python3.7/urllib/request.py", line 543, in _open,
    '_open', req),
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain,
    result = func(*args),
  File "/usr/local/lib/python3.7/urllib/request.py", line 1362, in https_open,
    context=self._context, check_hostname=self._check_hostname),
  File "/usr/local/lib/python3.7/urllib/request.py", line 1321, in do_open,
    raise URLError(err),
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'feeds.livep2000.nl'. (_ssl.c:1076)>,
```

**Comment by cyberjunky** [comment]
I have a fix by patching the ssl routine to ignore the invalid cert, testing it now, as soon as it fetches the first event I will upload it.

**Comment by poudenes** [comment]
Thanks for the fast fix!

**Comment by Martinvdm** [comment]
> I have a fix by patching the ssl routine to ignore the invalid cert, testing it now, as soon as it fetches the first event I will upload it.

i had created a fix by myself, are waiting for the event trigger also. i will compare mine with yours (just to learn :) ). thanks!

**Comment by cyberjunky** [comment]
Just uploaded it, I guess your solution is nicer.

**Comment by poudenes** [comment]
updated. Now wait when there is a new trigger (Amsterdam, almost every 5min so lets see)

**Comment by pdeelen** [comment]
thanks for your fast response and fix!
