### ISSUE TITLE
P2000 will not start

### ISSUE THREAD

**Issue by Tankdoz** [cyberjunky/home-assistant-p2000#27]
I turned on debugging, something appears to go wrong here:

2020-11-24 23:28:24 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/p2000/sensor.py", line 147, in async_update
event_time = self._convert_time(entry.published)
File "/config/custom_components/p2000/sensor.py", line 110, in _convert_time
return datetime.datetime.strptime(time.split(",")[1][:-6], " %d %b %Y %H:%M:%S")
IndexError: list index out of range

**Comment by groenmarsmannetje** [comment]
I also noticed this error during start up

**Comment by cyberjunky** [comment]
@Tankdoz @groenmarsmannetje No idea why the code is failing, but I added a check to the code, can you try version 1.0.18?

**Comment by groenmarsmannetje** [comment]
The index out of range error is still there. But now I noticed also this error:

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/p2000/sensor.py", line 151, in async_update
    if event_time < self._event_time:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'

**Comment by cyberjunky** [comment]
@groenmarsmannetje I somehow expected this to happen, the data fetched (or part of it) are clearly different than normal.
Can you share your p2000 config, the set timezone in home assistant and maybe enable p2000 debug and supply some data, so I can have a look what the real cause it, and make it more robust.

**Comment by groenmarsmannetje** [comment]
@cyberjunky see my configuration below:

```
  - platform: p2000
    name: Alphen aan den Rijn
    regios: 16
    disciplines: 1,2,3,4
    radius: 1000
    scan_interval: 30
  - platform: p2000
    name: Brandweer
    regios: 16
    disciplines: 1
    radius: 1000
    scan_interval: 30
    icon: mdi:fire-truck
  - platform: p2000
    name: Ambulance
    regios: 16
    disciplines: 2
    radius: 1000
    scan_interval: 30
    icon: mdi:ambulance
  - platform: p2000
    name: Politie
    regios: 16
    disciplines: 3
    radius: 1000
    scan_interval: 30
    icon: mdi:car-emergency
  - platform: p2000
    name: Reddingsbrigade
    regios: 16
    disciplines: 4
    radius: 1000
    scan_interval: 30
    icon: mdi:ferry
```

**Comment by groenmarsmannetje** [comment]
@cyberjunky and this is the debug of the log file with all lines containing "p2000" filtered.

[p2000_debug.txt](https://github.com/cyberjunky/home-assistant-p2000/files/6364610/p2000_debug.txt)

**Comment by dheuts90** [comment]
I'm having the same error message: "Error doing job: Task exception was never retrieved"

```
Logger: homeassistant
Source: custom_components/p2000/sensor.py:129
First occurred: 9:58:08 (175 occurrences)
Last logged: 10:34:00

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/local/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/p2000/sensor.py", line 129, in async_update
    self._feed = await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/feedparser/api.py", line 214, in parse
    data = _open_resource(url_file_stream_or_string, etag, modified, agent, referrer, handlers, request_headers, result)
  File "/usr/local/lib/python3.8/site-packages/feedparser/api.py", line 114, in _open_resource
    return http.get(url_file_stream_or_string, etag, modified, agent, referrer, handlers, request_headers, result)
  File "/usr/local/lib/python3.8/site-packages/feedparser/http.py", line 158, in get
    f = opener.open(request)
  File "/usr/local/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 1379, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Try again>
```

My configuration file:
```
- platform: p2000
  name: Brandweer Schinveld
  scan_interval: 20
  capcodes: 1004555,1004552,1004550
  icon: mdi:fire-truck
  nolocation: true
    
- platform: p2000
  name: P2000 Schinveld
  regios: 24
  radius: 10000
  scan_interval: 10
```

**Comment by cyberjunky** [comment]
Closing this old ticket for now, if this is still an issue please reopen.
